name: python-cicd-demo

on:
  push:
    branches:
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          pip3 install -r requeriments.txt

      - name: Test
        run: |
          pytest test/test.py