name: python-cicd-demo

on:
  push:
    branches:
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Test
        run: |
          pytest test/test.py

      - name: Docker Build
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/python-cicd-demo:${{github.sha}} .

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Docker Push
        run: |
          docker push ${{secrets.DOCKER_USERNAME}}/python-cicd-demo:${{github.sha}}

  cd: 
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: "Docker Pull"
        env: 
          DOCKER_IMAGE: ${{secrets.DOCKER_USERNAME}}/python-cicd-demo:${{github.sha}}
        run: |
          echo "Downloading new Docker img version..."
            docker pull $DOCKER_IMAGE

      - name: "Release"
        if: ${{ success() }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          tag_name: v${{ github.sha }}
          release_name: "Release ${{ github.sha }}"
          draft: false
          prerelease: ${{ contains('develop', github.ref_name) }}