name: python-cicd-demo

on:
  push:
    branches:
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Test
        run: |
          pytest test/test.py

      - name: Docker Build
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/python-cicd-demo:${{github.sha}} .

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Docker Push
        run: |
          docker push ${{secrets.DOCKER_USERNAME}}/python-cicd-demo:${{github.sha}}

  cd: 
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: "Deploy"
        uses: appleboy/ssh-action@master
        env:
          DOCKER_IMAGE: ${{secrets.DOCKER_USERNAME}}/python-cicd-demo:${{github.sha}}
        with:
          script: |
            echo "Downloading new Docker img version..."
            docker pull $DOCKER_IMAGE
            echo "Stopping current Docker img version..."
            sleep 1

      - name: Check Service
        run: |
          echo "Success!"